#!/usr/bin/env bash
#
# Copyright (C) 2017 Chunyang Xu
#
# web-search-test - Tests for web-search

set -o errexit

diff <(web-search -o hello world) <(echo 'https://www.google.com/search?q=hello%20world')
diff <(web-search -o -p reddit /r/emacs vim) <(echo 'https://www.reddit.com/r/emacs/search?q=vim&restrict_sr=on')
